import typing

from .client import Client
from .config import CertTypes, TimeoutTypes, VerifyTypes
from .models import (
    AuthTypes,
    CookieTypes,
    HeaderTypes,
    ProxiesTypes,
    QueryParamTypes,
    RequestData,
    RequestFiles,
    Response,
    URLTypes,
)


def request(
    method: str,
    url: URLTypes,
    *,
    params: typing.Optional[QueryParamTypes] = None,
    data: typing.Optional[RequestData] = None,
    files: typing.Optional[RequestFiles] = None,
    json: typing.Any = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    auth: typing.Optional[AuthTypes] = None,
    timeout: typing.Optional[TimeoutTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    stream: bool = False,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    with Client(http_versions=["HTTP/1.1"]) as client:
        return client.request(
            method=method,
            url=url,
            data=data,
            files=files,
            json=json,
            params=params,
            headers=headers,
            cookies=cookies,
            stream=stream,
            auth=auth,
            allow_redirects=allow_redirects,
            cert=cert,
            verify=verify,
            timeout=timeout,
            trust_env=trust_env,
        )


def get(
    url: URLTypes,
    *,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "GET",
        url,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def options(
    url: URLTypes,
    *,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "OPTIONS",
        url,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def head(
    url: URLTypes,
    *,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = False,  #  Note: Differs to usual default.
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "HEAD",
        url,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def post(
    url: URLTypes,
    *,
    data: typing.Optional[RequestData] = None,
    files: typing.Optional[RequestFiles] = None,
    json: typing.Any = None,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "POST",
        url,
        data=data,
        files=files,
        json=json,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def put(
    url: URLTypes,
    *,
    data: typing.Optional[RequestData] = None,
    files: typing.Optional[RequestFiles] = None,
    json: typing.Any = None,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "PUT",
        url,
        data=data,
        files=files,
        json=json,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def patch(
    url: URLTypes,
    *,
    data: typing.Optional[RequestData] = None,
    files: typing.Optional[RequestFiles] = None,
    json: typing.Any = None,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "PATCH",
        url,
        data=data,
        files=files,
        json=json,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )


def delete(
    url: URLTypes,
    *,
    params: typing.Optional[QueryParamTypes] = None,
    headers: typing.Optional[HeaderTypes] = None,
    cookies: typing.Optional[CookieTypes] = None,
    stream: bool = False,
    auth: typing.Optional[AuthTypes] = None,
    allow_redirects: bool = True,
    cert: typing.Optional[CertTypes] = None,
    verify: VerifyTypes = True,
    timeout: typing.Optional[TimeoutTypes] = None,
    trust_env: typing.Optional[bool] = None,
    proxies: typing.Optional[ProxiesTypes] = None,
) -> Response:
    return request(
        "DELETE",
        url,
        params=params,
        headers=headers,
        cookies=cookies,
        stream=stream,
        auth=auth,
        allow_redirects=allow_redirects,
        cert=cert,
        verify=verify,
        timeout=timeout,
        trust_env=trust_env,
    )
